[package]
name = "cloud_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
env_logger = "0.11.1"
log = "0.4.20"
once_cell = "1.19.0"
parking_lot = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = { version = "0.9.29", features = [] }
strum = "0.25.0"
strum_macros = "0.25.3"
tokio = "1.35.1"
tokio-test = "0.4.3"
uuid = { version = "1.6.1", features = ["serde", "v4"] }

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
