[package]
name = "cloud_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
env_logger = "0.11.0"
log = "0.4.20"
parking_lot = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = { version = "0.9.29", features = [] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }
