@startuml Component

skinparam backgroundColor white

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Cloud Scraper High Level Component Diagram

Container_Boundary(cloud_scraper, "Cloud Scraper") {
    Component(scraper, "Scraper Binary", "Scrapes cloud providers for data")
    ComponentDb(state, "Scraping State", "Stores the state of the scraping process")
    Container(config, "Scraper Config", "Stores the configuration for the scraper") {
        Component(general_config, "General Config")
        Component(source_config, "Source Config", "Stores the configuration for a cloud provider")
        Component(sink_config, "Sink Config", "Stores the configuration for a sink")
    }
}

Rel(scraper, state, "Synchronization state")
Rel(general_config, scraper, "Max request rate per source")
Rel(source_config, scraper, "Source authentication, source-specific config")
Rel(sink_config, scraper, "Sink authentication, sink-specific config")

@enduml
