# From https://doc.rust-lang.org/cargo/guide/continuous-integration.html
name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Cloud Scraper - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{matrix.toolchain}} && rustup default ${{matrix.toolchain}}
      - run: cargo build --verbose
      - run: cargo test --verbose
  latest_deps:
    name: Cloud Scraper - latest stable dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
