# From https://doc.rust-lang.org/cargo/guide/continuous-integration.html
name: Cargo Build & Test

on:
  push:

env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Cloud Scraper - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{matrix.toolchain}} && rustup default ${{matrix.toolchain}}
      - run: cargo build --verbose
      - run: cargo test --verbose
  coverage:
    name: Cloud Scraper - Coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: llvm-tools-preview
          override: true
          toolchain: stable
      - name: test with coverage
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Cinstrument-coverage'
          LLVM_PROFILE_FILE: 'cargo-test-%p-%m.profraw'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
      - name: install grcov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov
      - name: extract coverage
        run: grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/tests.lcov
      - name: upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: target/tests.lcov
          slug: rob-h-w/cloud-scraper
          verbose: true
  coding_standards:
    name: Cloud Scraper - Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo fmt --check --verbose
      - uses: DavidAnson/markdownlint-cli2-action@v14
  latest_deps:
    name: Cloud Scraper - latest stable dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
