# From https://doc.rust-lang.org/cargo/guide/continuous-integration.html
name: Cargo Build & Test

on:
  push:

env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Cloud Scraper - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Build and test with ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  coding_standards:
    name: Cloud Scraper - Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo fmt --check --verbose
      - uses: DavidAnson/markdownlint-cli2-action@v14
  latest_deps:
    name: Cloud Scraper - latest stable dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
